<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../../../../../../Development%20Workspace/BPM/PaymentApprovalProc/PaymentApproval/BP_SaveApprover.wsdl"/>
      <rootElement name="XxPaymentApprovalDataCollection_copy_1" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetApprovalData"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../../../../../../Development%20Workspace/BPM/PaymentApprovalProc/PaymentApproval/SaveApprover.wsdl"/>
      <rootElement name="XxPaymentApprovalHistoryCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/SaveApprover"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.8(build 150622.2350.0222) AT [WED APR 20 14:25:59 PKT 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/SaveApprover"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:client="http://xmlns.oracle.com/PaymentApprovalProcess/PaymentApproval/BP_SaveApprover"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PaymentApprovalProcess/PaymentApproval/SaveApprover"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetApprovalData"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plnk client wsdl xsd ns1 top tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <top:XxPaymentApprovalHistoryCollection>
      <xsl:for-each select="/ns1:XxPaymentApprovalDataCollection_copy_1/ns1:XxPaymentApprovalData">
        <top:XxPaymentApprovalHistory>
          <top:historyId>
            <xsl:value-of select='oraext:sequence-next-val("xx_pay_approval_history_Seq","jdbc:oracle:thin:apps/mskiz145@192.168.0.30:1526:icterp")'/>
          </top:historyId>
          <top:checkId>
            <xsl:value-of select="ns1:checkId"/>
          </top:checkId>
          <top:approverId>
            <xsl:value-of select="../ns1:approver"/>
          </top:approverId>
          <top:theTime>
            <xsl:value-of select="xp20:current-dateTime()"/>
          </top:theTime>
        </top:XxPaymentApprovalHistory>
      </xsl:for-each>
    </top:XxPaymentApprovalHistoryCollection>
  </xsl:template>
</xsl:stylesheet>
