<?binding.jca GET_MANAGER_db.jca?>
<wsdl:definitions name="GET_MANAGER" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PaymentApprovalProcess/PaymentApproval/GET_MANAGER" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PaymentApprovalProcess/PaymentApproval/GET_MANAGER" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GET_MANAGER">
    <plt:partnerLinkType name="GET_MANAGER_plt">
        <plt:role name="GET_MANAGER_role">
            <plt:portType name="tns:GET_MANAGER_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GET_MANAGER" schemaLocation="xsd/GET_MANAGER_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="GET_MANAGERSelect_inputParameters">
        <wsdl:part name="GET_MANAGERSelect_inputParameters" element="top:GET_MANAGERSelect_hierarchy_nameInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XxGrnAprMgrCollection_msg">
        <wsdl:part name="XxGrnAprMgrCollection" element="top:XxGrnAprMgrCollection"/>
    </wsdl:message>
    <wsdl:portType name="GET_MANAGER_ptt">
        <wsdl:operation name="GET_MANAGERSelect">
            <wsdl:input message="tns:GET_MANAGERSelect_inputParameters"/>
            <wsdl:output message="tns:XxGrnAprMgrCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
