<?binding.jca UpdateFlags_db.jca?>
<wsdl:definitions name="UpdateFlags" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/PaymentApprovalProcess/PaymentApproval/UpdateFlags" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PaymentApprovalProcess/PaymentApproval/UpdateFlags" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateFlags">
    <plt:partnerLinkType name="UpdateFlags_plt">
        <plt:role name="UpdateFlags_role">
            <plt:portType name="tns:UpdateFlags_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateFlags" schemaLocation="xsd/UpdateFlags_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ApChecksAllCollection_msg">
        <wsdl:part name="ApChecksAllCollection" element="top:ApChecksAllCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateFlags_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:ApChecksAllCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
